version: 2.1
jobs:
  build:
    working_directory: ~/phone-book
    docker:
      - image: cimg/node:20.19.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-yarn-cache-node20-{{ checksum "yarn.lock" }}
            - v2-yarn-cache-node20-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: v2-yarn-cache-node20-{{ checksum "yarn.lock" }}
      - run:
          name: Initialize data
          command: node load-initial-data.js

  lint:
    working_directory: ~/phone-book
    docker:
      - image: cimg/node:20.19.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-yarn-cache-node20-{{ checksum "yarn.lock" }}
            - v2-yarn-cache-node20-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Run linter
          command: yarn lint

  test:
    working_directory: ~/phone-book
    docker:
      - image: cimg/node:20.19.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-yarn-cache-node20-{{ checksum "yarn.lock" }}
            - v2-yarn-cache-node20-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Initialize data
          command: node load-initial-data.js
      - run:
          name: Run tests
          command: yarn test

  coverage:
    working_directory: ~/phone-book
    docker:
      - image: cimg/node:20.19.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-yarn-cache-node20-{{ checksum "yarn.lock" }}
            - v2-yarn-cache-node20-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Initialize data
          command: node load-initial-data.js
      - run:
          name: Generate coverage report
          command: yarn coverage
      - store_artifacts:
          path: coverage
          destination: coverage-report

workflows:
  version: 2
  build_test_coverage:
    jobs:
      - build
      - lint
      - test:
          requires:
            - build
      - coverage:
          requires:
            - build
